---
framework: mocha  
preRun:
  command:
    - npm install  
preMerge:
  pattern:
    - "./test/acceptance/*.js"
    - "./test/app.options.js"
    - "./test/Router.js"
postMerge:
  pattern: 
    - "./test/acceptance/*.js"
    - "./test/app.options.js"
    - "./test/Router.js"
postRun:
  command:
    - node --version
configFile: mocharc.yml
version : 1.0.1
